### ISSUE TITLE
Scoreboard Warning

### ISSUE THREAD

**Issue by ChrisJLKC** [ChrisJLKC/Java_Minecraft_Plugins#1]
[WARN]: [scoreboards] Task #5 for scoreboards v1.0.0 generated an exception
java.lang.NullPointerException: null
	at me.chris.hubscoreboards.main$1.run(main.java:119) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2995-Spigot-5bde311-0bad58f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

Warning as stated above

**Comment by ChrisJLKC** [comment]
Sorted issue
